trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

- task: PowerShell@2
  displayName: 'GitVersion'
  inputs:
    targetType: 'inline'
    script: 'gitversion /l console /output buildserver /updateAssemblyInfo'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '*.sln'
    arguments: '-c Release "/p:Version=$(GitVersion.MajorMinorPatch)" -r win-x86'

- task: CmdLine@2
  displayName: 'Run unit tests'
  inputs:
    script: 'dotnet test ./Rx.Nyss.Web.Tests/Rx.Nyss.Web.Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish WebApp'
  inputs:
    command: publish
    publishWebProjects: false
    arguments: './src/RX.Nyss.Web/RX.Nyss.Web.csproj -c Release -o "$(Build.ArtifactStagingDirectory)/webapp" --no-build --self-contained -r win-x86'
    zipAfterPublish: true
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: 'Publish ConsoleApp for DB migration'
  inputs:
    command: publish
    publishWebProjects: false
    arguments: './src/RX.Nyss.Data.MigrationApp/RX.Nyss.Data.MigrationApp.csproj -c Release -o "$(Build.ArtifactStagingDirectory)/migrationapp" --no-build -r win-x86'
    zipAfterPublish: false
    modifyOutputPath: false

- task: CopyFiles@2
  inputs:
    SourceFolder: 'Infrastructure'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Infrastructure'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
